# Generated by Django 4.1 on 2025-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileauthuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileauthuser',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileauthuser',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileauthuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_auth/profile_images/'),
        ),
    ]
