# Generated by Django 4.1 on 2025-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0002_mobileauthuser_address_mobileauthuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileauthuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_user/mobile_auth/profile_images/'),
        ),
    ]
