# Generated by Django 4.1 on 2025-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0003_alter_mobileauthuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileauthuser',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
