# Generated by Django 4.1 on 2025-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0004_mobileauthuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileauthuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
