# Generated by Django 4.1 on 2025-10-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0005_alter_mobileauthuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMTokenWiseUpdatedLatLon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FCM Token Wise Updated Lat Lon',
                'verbose_name_plural': 'FCM Tokens Wise Updated Lat Lon',
            },
        ),
    ]
