# Generated by Django 4.1 on 2026-04-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0061_bmdwrfpremonsoonbasinwiseflashfloodforecast'),
        ('app_user_mobile', '0006_fcmtokenwiseupdatedlatlon'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelSync',
            fields=[
            ],
            options={
                'verbose_name': 'Water Level API Sync',
                'verbose_name_plural': 'Water Level API Sync',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_load.waterlevelobservation',),
        ),
    ]
