# Generated by Django 4.1 on 2026-04-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0061_bmdwrfpremonsoonbasinwiseflashfloodforecast'),
        ('app_user_mobile', '0007_waterlevelsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallSync',
            fields=[
            ],
            options={
                'verbose_name': 'Rainfall API Sync',
                'verbose_name_plural': 'Rainfall API Sync',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_load.rainfallobservation',),
        ),
    ]
