# Generated by Django 4.1 on 2026-04-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0008_rainfallsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'RIMES SMS (Data Parser & Sync)',
                'verbose_name_plural': 'RIMES SMS (Data Parser & Sync)',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mobileauthuser',
            options={'verbose_name': 'Auth User', 'verbose_name_plural': 'Auth Users'},
        ),
        migrations.AlterModelOptions(
            name='rainfallsync',
            options={'verbose_name': 'LEOTECH SMS(Rainfall) API Sync', 'verbose_name_plural': 'LEOTECH SMS(Rainfall) API Sync'},
        ),
        migrations.AlterModelOptions(
            name='waterlevelsync',
            options={'verbose_name': 'LEOTECH SMS (Waterlevel) API Sync', 'verbose_name_plural': 'LEOTECH SMS (Waterlevel) API Sync'},
        ),
    ]
