# Generated by Django 4.2.23 on 2025-06-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'basins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('station_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bwdb_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('ffdata_header', models.CharField(blank=True, max_length=50, null=True)),
                ('ffdata_header_1', models.CharField(blank=True, max_length=50, null=True)),
                ('river', models.CharField(max_length=50)),
                ('river_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('river_chainage', models.FloatField(blank=True, null=True)),
                ('basin_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('danger_level', models.FloatField(blank=True, null=True)),
                ('pmdl', models.CharField(blank=True, max_length=10, null=True)),
                ('highest_water_level', models.FloatField(blank=True, null=True)),
                ('highest_water_level_date', models.DateField(blank=True, null=True)),
                ('gauge_shift', models.FloatField(blank=True, null=True)),
                ('gauge_factor', models.FloatField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('h_division', models.CharField(blank=True, max_length=50, null=True)),
                ('h_division_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(max_length=50)),
                ('division_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=50)),
                ('district_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('union', models.CharField(blank=True, max_length=50, null=True)),
                ('union_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('five_days_forecast', models.BooleanField(blank=True, null=True)),
                ('ten_days_forecast', models.BooleanField(blank=True, null=True)),
                ('monsoon_station', models.BooleanField(blank=True, null=True)),
                ('pre_monsoon_station', models.BooleanField(blank=True, null=True)),
                ('dry_period_station', models.BooleanField(blank=True, null=True)),
                ('sms_id', models.CharField(blank=True, max_length=10, null=True)),
                ('msi_date', models.DateField(blank=True, null=True)),
                ('msi_year', models.IntegerField(blank=True, null=True)),
                ('order_up_down', models.IntegerField(blank=True, null=True)),
                ('forecast_observation', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('station_order', models.IntegerField(blank=True, null=True)),
                ('medium_range_station', models.BooleanField(blank=True, null=True)),
                ('jason_2_satellite_station', models.BooleanField(blank=True, null=True)),
                ('experimental', models.BooleanField(blank=True, null=True)),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_load.basin')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_load.unit')),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
                'indexes': [models.Index(fields=['name'], name='idx_station_name'), models.Index(fields=['station_code'], name='idx_station_st_code'), models.Index(fields=['basin'], name='idx_basin_id'), models.Index(fields=['station_id'], name='idx_station_id')],
            },
        ),
        migrations.CreateModel(
            name='RainfallStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('station_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('basin_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('division_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('district_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_load.basin')),
            ],
            options={
                'db_table': 'rainfall_stations',
                'managed': True,
                'indexes': [models.Index(fields=['station_code'], name='idx_rainfall_st_code'), models.Index(fields=['name'], name='idx_name'), models.Index(fields=['station_id'], name='idx_rainfall_station_id')],
            },
        ),
    ]
