# Generated by Django 4.2.23 on 2025-06-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WaterLevelObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField()),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_experimental', models.BooleanField(default=False)),
                ('station_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_load.station', to_field='station_id')),
            ],
            options={
                'db_table': 'water_level_observations',
                'managed': True,
                'indexes': [models.Index(fields=['station_id', 'observation_date'], name='idx_waterlevel_station_id_date')],
            },
        ),
        migrations.CreateModel(
            name='WaterLevelForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateTimeField()),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_load.station', to_field='station_id')),
            ],
            options={
                'db_table': 'water_level_forecasts',
                'managed': True,
                'indexes': [models.Index(fields=['station_id', 'forecast_date'], name='idx_station_id_forecast_date')],
            },
        ),
        migrations.CreateModel(
            name='RainfallObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField()),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=8)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_load.rainfallstation')),
            ],
            options={
                'db_table': 'rainfall_observations',
                'managed': True,
                'indexes': [models.Index(fields=['station_id', 'observation_date'], name='idx_rainfall_station_id_date')],
            },
        ),
    ]
