# Generated by Django 4.2.23 on 2025-06-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0002_alter_station_station_id_waterlevelobservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlevelobservation',
            name='is_experimental',
        ),
    ]
