# Generated by Django 4.2.23 on 2025-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0004_ffwcstations_ffwcstations2023_ffwcstations2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='river_chainage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
