# Generated by Django 4.2.23 on 2025-06-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0005_alter_station_river_chainage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
