# Generated by Django 4.2.23 on 2025-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0006_alter_basin_id_alter_station_id_alter_unit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfwcRainfallStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('basin_order', models.IntegerField()),
                ('basin', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=10)),
                ('union', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('lat_wgs84', models.DecimalField(decimal_places=8, max_digits=12)),
                ('long_wgs84', models.DecimalField(decimal_places=8, max_digits=12)),
                ('station_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ffwc_rainfall_stations_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FfwcRainfallStations2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(blank=True, max_length=10, null=True)),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('basin', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('dtation_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('basin_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('division_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('district_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla_bn', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ffwc_rainfall_stations_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FfwcRainfallStationsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('basin', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ffwc_rainfall_stations',
                'managed': False,
            },
        ),
    ]
