# Generated by Django 4.2.23 on 2025-06-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0007_ffwcrainfallstations_ffwcrainfallstations2025_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FfwcRainfallStations',
        ),
        migrations.DeleteModel(
            name='FfwcRainfallStations2025',
        ),
        migrations.DeleteModel(
            name='FfwcRainfallStationsNew',
        ),
        migrations.DeleteModel(
            name='FfwcStations',
        ),
        migrations.DeleteModel(
            name='FfwcStations2023',
        ),
        migrations.DeleteModel(
            name='FfwcStations2025',
        ),
    ]
