# Generated by Django 4.2.23 on 2025-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0008_delete_ffwcrainfallstations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfwcLastUpdateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField()),
                ('entry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ffwc_last_update_date',
                'managed': True,
            },
        ),
    ]
