# Generated by Django 4.2.23 on 2025-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0009_ffwclastupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffwclastupdatedate',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
