# Generated by Django 4.2.23 on 2025-06-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0010_alter_ffwclastupdatedate_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfallstation',
            name='basin_bn',
        ),
    ]
