# Generated by Django 4.2.23 on 2025-06-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0011_remove_rainfallstation_basin_bn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='basin_bn',
        ),
    ]
