# Generated by Django 4.2.23 on 2025-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0012_remove_station_basin_bn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='ScrollerMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scroller_messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecondScrollerMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'second_scroller_messages',
                'managed': True,
            },
        ),
    ]
