# Generated by Django 4.2.23 on 2025-06-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0013_messages_scrollermessages_secondscrollermessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('month_serial', models.IntegerField()),
                ('month_name', models.CharField(max_length=15)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('max_rainfall', models.DecimalField(decimal_places=2, max_digits=8)),
                ('normal_rainfall', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_rainfall', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Monthly Rainfall',
                'verbose_name_plural': 'Monthly Rainfalls',
                'db_table': 'monthly_rainfall',
                'managed': True,
            },
        ),
    ]
