# Generated by Django 4.2.23 on 2025-07-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0014_monthlyrainfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelForecastsExperimentals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateTimeField()),
                ('waterlevel_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waterlevel_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waterlevel_mean', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_load.station', to_field='station_id')),
            ],
            options={
                'verbose_name': 'Experimental Water Level Forecast',
                'verbose_name_plural': 'Experimental Water Level Forecasts',
                'db_table': 'water_level_forecast_experimentals',
                'managed': True,
                'indexes': [models.Index(fields=['station_id', 'forecast_date'], name='idx_exp_stid_fcdate')],
            },
        ),
    ]
