# Generated by Django 4.2.23 on 2025-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0015_waterlevelforecastsexperimentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfwcLastUpdateDateExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ffwc_last_update_date_experimental',
                'managed': True,
            },
        ),
    ]
