# data_load/migrations/0017_auto_20250703_0255.py (Your actual file name may vary)

# Generated by Django 4.2.23 on 2025-07-03 02:55

from django.db import migrations, models

# The function that performs the data migration
def recreate_basins_and_update_fks(apps, schema_editor):
    Basin = apps.get_model('data_load', 'Basin')
    Station = apps.get_model('data_load', 'Station')
    RainfallStation = apps.get_model('data_load', 'RainfallStation')

    # 1. Define the mapping from old IDs to new sequential IDs and store full data
    basin_new_data = {
        1: {'new_id': 1, 'name': 'Brahmaputra', 'name_bn': 'বহ্মপুত্র'},
        3: {'new_id': 2, 'name': 'Ganges', 'name_bn': 'গঙ্গা'},
        4: {'new_id': 3, 'name': 'Meghna', 'name_bn': 'মেঘনা'},
        5: {'new_id': 4, 'name': 'SE Hill', 'name_bn': 'দক্ষিণ-পূর্ব পার্বত্য'},
    }

    # 2. Collect existing foreign key relationships based on their OLD basin_id
    station_old_to_new_basin_id_map = {}
    for station in Station.objects.filter(basin__id__in=basin_new_data.keys()):
        station_old_to_new_basin_id_map[station.id] = basin_new_data[station.basin_id]['new_id']

    rainfall_station_old_to_new_basin_id_map = {}
    for r_station in RainfallStation.objects.filter(basin__id__in=basin_new_data.keys()):
        rainfall_station_old_to_new_basin_id_map[r_station.id] = basin_new_data[r_station.basin_id]['new_id']

    # 3. Nullify ALL foreign keys in Station and RainfallStation
    print("Setting all Station basin_ids to NULL...")
    Station.objects.update(basin=None)
    print("Setting all RainfallStation basin_ids to NULL...")
    RainfallStation.objects.update(basin=None)

    # 4. Delete ALL existing Basin records
    print("Deleting all existing Basin records...")
    Basin.objects.all().delete()

    # 5. Create new Basin records with the desired new IDs (1, 2, 3, 4)
    # The ALTER TABLE commands below will implicitly commit.
    # This whole RunPython operation will now run outside a transaction due to atomic=False.
    
    print("Resetting AUTO_INCREMENT for basins table to 1 (for MySQL)...")
    schema_editor.execute("ALTER TABLE `basins` AUTO_INCREMENT = 1;")

    print("Creating new Basin records with desired IDs...")
    for old_id, data in basin_new_data.items():
        new_id = data['new_id']
        name = data['name']
        name_bn = data['name_bn']
        
        schema_editor.execute(
            f"INSERT INTO `basins` (`id`, `name`, `name_bn`) VALUES ({new_id}, '{name}', '{name_bn}');"
        )
    
    # 6. Re-link Station and RainfallStation records to the new Basin objects
    print("Re-linking Station records to new Basin objects...")
    for station_id, new_basin_id in station_old_to_new_basin_id_map.items():
        try:
            new_basin_obj = Basin.objects.get(id=new_basin_id)
            Station.objects.filter(id=station_id).update(basin=new_basin_obj)
        except Basin.DoesNotExist:
            print(f"Error: New Basin ID {new_basin_id} not found when re-linking station {station_id}.")
        except Station.DoesNotExist:
            print(f"Error: Station ID {station_id} not found during re-linking.")


    print("Re-linking RainfallStation records to new Basin objects...")
    for r_station_id, new_basin_id in rainfall_station_old_to_new_basin_id_map.items():
        try:
            new_basin_obj = Basin.objects.get(id=new_basin_id)
            RainfallStation.objects.filter(id=r_station_id).update(basin=new_basin_obj)
        except Basin.DoesNotExist:
            print(f"Error: New Basin ID {new_basin_id} not found when re-linking rainfall station {r_station_id}.")
        except RainfallStation.DoesNotExist:
            print(f"Error: RainfallStation ID {r_station_id} not found during re-linking.")

    # 7. Reset AUTO_INCREMENT sequence for `basins` table for future inserts
    max_id = Basin.objects.aggregate(max_id=models.Max('id'))['max_id']
    if max_id is not None:
        print(f"Resetting AUTO_INCREMENT for basins to {max_id + 1}...")
        schema_editor.execute(f"ALTER TABLE `basins` AUTO_INCREMENT = {max_id + 1};")
    else:
        print("Basins table is empty after migration. Resetting AUTO_INCREMENT to 1.")
        schema_editor.execute(f"ALTER TABLE `basins` AUTO_INCREMENT = 1;")


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0016_ffwclastupdatedateexperimental'),
    ]

    operations = [
        # *** THIS IS THE CRITICAL CHANGE ***
        # Set atomic=False because DDL statements like ALTER TABLE implicitly commit transactions in MySQL.
        migrations.RunPython(recreate_basins_and_update_fks, atomic=False),
    ]