# Generated by Django 4.2.23 on 2025-07-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0017_auto_20250703_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basin',
            options={'managed': True, 'verbose_name': 'River Basin', 'verbose_name_plural': 'River Basins'},
        ),
        migrations.AlterModelOptions(
            name='ffwclastupdatedate',
            options={'managed': True, 'verbose_name': 'Last Update Date', 'verbose_name_plural': 'Last Update Dates'},
        ),
        migrations.AlterModelOptions(
            name='ffwclastupdatedateexperimental',
            options={'managed': True, 'verbose_name': 'Experimental Last Update Date', 'verbose_name_plural': 'Experimental Last Update Dates'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message Item', 'verbose_name_plural': 'Message Items'},
        ),
        migrations.AlterModelOptions(
            name='rainfallobservation',
            options={'managed': True, 'verbose_name': 'Rainfall Observation', 'verbose_name_plural': 'Rainfall Observations'},
        ),
        migrations.AlterModelOptions(
            name='rainfallstation',
            options={'managed': True, 'verbose_name': 'Rainfall Monitoring Station', 'verbose_name_plural': 'Rainfall Monitoring Stations'},
        ),
        migrations.AlterModelOptions(
            name='scrollermessages',
            options={'managed': True, 'verbose_name': 'Scroller Message', 'verbose_name_plural': 'Scroller Messages'},
        ),
        migrations.AlterModelOptions(
            name='secondscrollermessages',
            options={'managed': True, 'verbose_name': 'Secondary Scroller Message', 'verbose_name_plural': 'Secondary Scroller Messages'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'managed': True, 'verbose_name': 'Monitoring Station', 'verbose_name_plural': 'Monitoring Stations'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'managed': True, 'verbose_name': 'Measurement Unit', 'verbose_name_plural': 'Measurement Units'},
        ),
        migrations.AlterModelOptions(
            name='waterlevelforecast',
            options={'managed': True, 'verbose_name': 'Water Level Forecast', 'verbose_name_plural': 'Water Level Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='waterlevelobservation',
            options={'managed': True, 'verbose_name': 'Water Level Observation', 'verbose_name_plural': 'Water Level Observations'},
        ),
    ]
