# Generated by Django 4.2.23 on 2025-07-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0018_alter_basin_options_alter_ffwclastupdatedate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterlevelforecastsexperimentals',
            options={'managed': True, 'verbose_name': 'Water Level Forecast (Experimental)', 'verbose_name_plural': 'Water Level Forecasts (Experimental)'},
        ),
    ]
