# Generated by Django 4.2.23 on 2025-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0019_alter_waterlevelforecastsexperimentals_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevelforecastsexperimentals',
            name='waterlevel_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='waterlevelforecastsexperimentals',
            name='waterlevel_mean',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='waterlevelforecastsexperimentals',
            name='waterlevel_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
