# Generated by Django 4.2.23 on 2025-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0020_alter_waterlevelforecastsexperimentals_waterlevel_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsoonBasinWiseFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'monsoon_basin_wise_flash_flood_forecast',
                'managed': False,
            },
        ),
    ]
