# Generated by Django 4.2.23 on 2025-07-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0021_monsoonbasinwiseflashfloodforecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monsoonbasinwiseflashfloodforecast',
            options={'managed': True},
        ),
    ]
