# Generated by Django 4.2.23 on 2025-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0022_alter_monsoonbasinwiseflashfloodforecast_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdBasins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basin_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'threshold_basins',
                'managed': True,
            },
        ),
    ]
