# Generated by Django 4.2.23 on 2025-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0023_thresholdbasins'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsoonProbabilisticFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'monsoon_probabilistic_flash_flood_forecast',
                'managed': True,
            },
        ),
    ]
