# Generated by Django 4.2.23 on 2025-07-05 17:39

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0024_monsoonprobabilisticflashfloodforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date of the flood report', unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('api_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='data_load_f_report__0e9fa8_idx')],
            },
        ),
    ]
