# Generated by Django 4.2.23 on 2025-07-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0025_floodreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(unique=True)),
                ('forecast_dates', models.JSONField()),
                ('generated_at', models.DateTimeField()),
                ('data_source', models.URLField(max_length=500)),
                ('total_districts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FloodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('districts', models.JSONField()),
                ('priority', models.IntegerField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='data_load.floodmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FloodForecastTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('persisting_severe', 'Persisting Severe'), ('worsening', 'Worsening'), ('improving', 'Improving'), ('new_alerts', 'New Alerts')], max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('current_alert', models.CharField(max_length=50)),
                ('future_alert', models.CharField(max_length=50)),
                ('forecast_date', models.DateField()),
                ('change', models.CharField(max_length=50)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_trends', to='data_load.floodmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FloodForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('district', models.CharField(max_length=50)),
                ('alert_type', models.CharField(max_length=50)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_data', to='data_load.floodmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FloodCurrentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('severe_flood', 'Severe Flood'), ('moderate_flood', 'Moderate Flood'), ('normal_conditions', 'Normal Conditions')], max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('alert_type', models.CharField(max_length=50)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_conditions', to='data_load.floodmetadata')),
            ],
        ),
    ]
