# Generated by Django 4.2.23 on 2025-07-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0026_floodmetadata_floodrecommendation_floodforecasttrend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodforecastdata',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='floodforecasttrend',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='floodrecommendation',
            name='metadata',
        ),
        migrations.DeleteModel(
            name='FloodCurrentCondition',
        ),
        migrations.DeleteModel(
            name='FloodForecastData',
        ),
        migrations.DeleteModel(
            name='FloodForecastTrend',
        ),
        migrations.DeleteModel(
            name='FloodMetadata',
        ),
        migrations.DeleteModel(
            name='FloodRecommendation',
        ),
    ]
