# Generated by Django 4.2.23 on 2025-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0027_remove_floodforecastdata_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('summary_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
