# Generated by Django 4.2.23 on 2025-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0028_floodsummaryreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floodsummaryreport',
            options={'ordering': ['-report_date'], 'verbose_name': 'Flood Summary Report', 'verbose_name_plural': 'Flood Summary Reports'},
        ),
        migrations.AlterField(
            model_name='floodsummaryreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was first generated.'),
        ),
        migrations.AlterField(
            model_name='floodsummaryreport',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Time taken to generate the report in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='floodsummaryreport',
            name='report_date',
            field=models.DateField(help_text='The date for which the flood summary report is generated.', unique=True),
        ),
        migrations.AlterField(
            model_name='floodsummaryreport',
            name='summary_data',
            field=models.JSONField(help_text='Stores the comprehensive flood summary report data in JSON format.'),
        ),
    ]
