# Generated by Django 4.2.23 on 2025-07-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0029_alter_floodsummaryreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelObservationExperimentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField()),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_load.station', to_field='station_id')),
            ],
            options={
                'verbose_name': 'Water Level Observation (Experimental)',
                'verbose_name_plural': 'Water Level Observations (Experimental)',
                'db_table': 'water_level_observation_experimentals',
                'managed': True,
                'indexes': [models.Index(fields=['station_id', 'observation_date'], name='idx_exp_obs_stid_obsdate')],
            },
        ),
    ]
