# Generated by Django 4.2.23 on 2025-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0030_waterlevelobservationexperimentals'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='waterlevelobservationexperimentals',
            constraint=models.UniqueConstraint(fields=('station_id', 'observation_date'), name='unique_experimental_observation'),
        ),
    ]
