# Generated by Django 4.2.23 on 2025-07-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0031_waterlevelobservationexperimentals_unique_experimental_observation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='waterlevelforecastsexperimentals',
            constraint=models.UniqueConstraint(fields=('station_id', 'forecast_date'), name='unique_experimental_forecast'),
        ),
    ]
