# Generated by Django 4.2.23 on 2025-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0032_waterlevelforecastsexperimentals_unique_experimental_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='extended_range_station',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
