# Generated by Django 4.2.23 on 2025-07-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0033_station_extended_range_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterlevelAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_no', models.IntegerField(unique=True)),
                ('alert_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Water Level Alert',
                'verbose_name_plural': 'Water Level Alerts',
                'db_table': 'waterlevel_alert',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DistrictFloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField()),
                ('district_name', models.CharField(max_length=100)),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_load.waterlevelalert', to_field='alert_type')),
            ],
            options={
                'verbose_name': 'District Flood Alert',
                'verbose_name_plural': 'District Flood Alerts',
                'db_table': 'district_flood_alert',
                'managed': True,
                'unique_together': {('alert_date', 'district_name', 'alert_type')},
            },
        ),
    ]
