# Generated by Django 4.2.23 on 2025-07-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0034_waterlevelalert_districtfloodalert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='districtfloodalert',
            unique_together={('alert_date', 'district_name')},
        ),
    ]
