# Generated by Django 4.2.23 on 2025-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0035_alter_districtfloodalert_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floodmaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='floodMaps/')),
            ],
            options={
                'db_table': 'floodmaps',
            },
        ),
    ]
