# Generated by Django 4.2.23 on 2025-08-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0036_floodmaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsoonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_year', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'monsoon_config',
                'managed': True,
                'unique_together': {('config_year', 'title')},
            },
        ),
    ]
