# Generated by Django 4.2.23 on 2025-08-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0037_monsoonconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waterlevelforecast',
            unique_together={('station_id', 'forecast_date')},
        ),
    ]
