# Generated by Django 4.1 on 2025-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0038_alter_waterlevelforecast_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
