# Generated by Django 4.1 on 2025-08-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0039_station_station_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodAlertDisclaimer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Flood Alerts Disclaimer Item',
                'verbose_name_plural': 'Flood Alerts Disclaimer Items',
                'db_table': 'FloodAlertDisclaimer',
            },
        ),
    ]
