# Generated by Django 4.1 on 2025-08-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0040_floodalertdisclaimer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='floodalertdisclaimer',
            table='flood_alert_disclaimer',
        ),
    ]
