# Generated by Django 4.1 on 2025-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0041_alter_floodalertdisclaimer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinRelatedManue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('title_bn', models.CharField(max_length=1024)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'Bulletin Related Manue',
                'verbose_name_plural': 'Bulletin Related Manues',
            },
        ),
        migrations.AlterModelOptions(
            name='floodalertdisclaimer',
            options={'verbose_name': 'Flood Alerts Disclaimer Item', 'verbose_name_plural': 'Flood Alerts Disclaimer'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message Item', 'verbose_name_plural': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='scrollermessages',
            options={'verbose_name': 'Scroller Message', 'verbose_name_plural': 'Scroller Messages'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'managed': True, 'verbose_name': 'Waterlevel Station', 'verbose_name_plural': 'Waterlevel Stations'},
        ),
    ]
