# Generated by Django 4.1 on 2025-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0042_bulletinrelatedmanue_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['station_serial_no'], name='stations_station_bc7180_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['observation_date'], name='water_level_observa_05d9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['station_id'], name='water_level_station_ff8045_idx'),
        ),
    ]
