# Generated by Django 4.1 on 2025-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0043_station_stations_station_bc7180_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSummaryMobileV1',
            fields=[
                ('station_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('station_pk', models.BigIntegerField(null=True)),
                ('station_code', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('name_bn', models.CharField(max_length=1024, null=True)),
                ('station_serial_no', models.IntegerField(null=True)),
                ('danger_level', models.FloatField(null=True)),
                ('highest_water_level', models.FloatField(null=True)),
                ('highest_water_level_date', models.DateTimeField(null=True)),
                ('gauge_shift', models.FloatField(null=True)),
                ('h_division', models.CharField(max_length=255, null=True)),
                ('h_division_bn', models.CharField(max_length=255, null=True)),
                ('division', models.CharField(max_length=255, null=True)),
                ('division_bn', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('district_bn', models.CharField(max_length=255, null=True)),
                ('upazilla', models.CharField(max_length=255, null=True)),
                ('upazilla_bn', models.CharField(max_length=255, null=True)),
                ('union', models.CharField(max_length=255, null=True)),
                ('union_bn', models.CharField(max_length=255, null=True)),
                ('river', models.CharField(max_length=255, null=True)),
                ('river_bn', models.CharField(max_length=255, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('five_days_forecast', models.BooleanField(blank=True, null=True)),
                ('ten_days_forecast', models.BooleanField(blank=True, null=True)),
                ('monsoon_station', models.BooleanField(blank=True, null=True)),
                ('pre_monsoon_station', models.BooleanField(blank=True, null=True)),
                ('dry_period_station', models.BooleanField(blank=True, null=True)),
                ('basin', models.CharField(max_length=255, null=True)),
                ('basin_bn', models.CharField(max_length=255, null=True)),
                ('last_water_level', models.FloatField(null=True)),
                ('last_observation_date', models.DateTimeField(null=True)),
                ('previous_water_level', models.FloatField(null=True)),
                ('previous_observation_date', models.DateTimeField(null=True)),
                ('level_difference', models.FloatField(null=True)),
                ('status_name', models.CharField(max_length=32, null=True)),
                ('water_level_24_hours_ago', models.FloatField(null=True)),
                ('water_level_24_hours_ago_observation_date', models.DateTimeField(null=True)),
                ('difference_water_level_24_hours', models.FloatField(null=True)),
                ('station_flood_status', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'station_summary_view_mobile_v1',
                'ordering': ['station_serial_no'],
                'managed': False,
            },
        ),
    ]
