# Generated by Django 4.1 on 2025-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0044_stationsummarymobilev1'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='waterlevelobservation',
            name='idx_waterlevel_station_id_date',
        ),
        migrations.RemoveIndex(
            model_name='waterlevelobservation',
            name='water_level_observa_05d9ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='waterlevelobservation',
            name='water_level_station_ff8045_idx',
        ),
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['station_id', '-observation_date'], name='idx_wtrlvl_st_id_date_desc'),
        ),
    ]
