# Generated by Django 4.1 on 2025-09-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0045_remove_waterlevelobservation_idx_waterlevel_station_id_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['station_id', 'observation_date'], name='idx_waterlevel_station_id_date'),
        ),
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['observation_date'], name='water_level_observa_05d9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['station_id'], name='water_level_station_ff8045_idx'),
        ),
    ]
