# Generated by Django 4.1 on 2025-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0047_stationsummaryviewmobilev1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='A unique identifier for the task', max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck this to disable the scheduled task.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scheduled Task Status',
                'verbose_name_plural': 'Scheduled Task Statuses',
            },
        ),
    ]
