# Generated by Django 4.1 on 2025-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0048_scheduledtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictFloodAlertAutoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('auto_update', models.BooleanField(default=True)),
            ],
        ),
    ]
