# Generated by Django 4.1 on 2025-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0050_jsonentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonentry',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='jsonentry',
            name='last_update_date',
        ),
        migrations.AddField(
            model_name='jsonentry',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
