# Generated by Django 4.1 on 2025-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0052_ukmetmonsoonbasinwiseflashfloodforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKMetMonsoonProbabilisticFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'ukmet_monsoon_probabilistic_flash_flood_forecast',
                'managed': True,
            },
        ),
    ]
