# Generated by Django 4.1 on 2025-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0053_ukmetmonsoonprobabilisticflashfloodforecast'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='waterlevelobservation',
            index=models.Index(fields=['-station_id', '-observation_date'], name='-idx_wtrl_sta_id_dt_wlo'),
        ),
    ]
