# Generated by Django 4.1 on 2026-02-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0055_bmdwrfmonsoonbasinwiseflashfloodforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsModelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, help_text='The ID of the station.', null=True)),
                ('date', models.DateTimeField(blank=True, help_text='The date and time for which the model was chosen.', null=True)),
                ('model_name', models.CharField(blank=True, help_text="The name of the chosen model (e.g., 'ECMWF-ENS', 'GEFS').", max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Ensemble Model Choice',
                'verbose_name_plural': 'Ensemble Model Choices',
                'db_table': 'ens_model_choice',
            },
        ),
    ]
