# Generated by Django 4.1 on 2026-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0056_ensmodelchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basin_Wise_Flash_Flood_Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
