# Generated by Django 4.1 on 2026-03-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0056_ensmodelchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlevelobservation',
            name='gauge_reader_water_level',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
