# Generated by Django 4.1 on 2026-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0058_probabilistic_flash_flood_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECMWF_1_PreMonsoonBasinWiseFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'ecmwf_1_pre_monsoon_basin_wise_flash_flood_forecast',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UKMetPreMonsoonBasinWiseFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'ukmet_pre_monsoon_basin_wise_flash_flood_forecast',
                'managed': True,
            },
        ),
    ]
