# Generated by Django 4.1 on 2026-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0059_ecmwf_1_premonsoonbasinwiseflashfloodforecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKMetPreMonsoonProbabilisticFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'ukmet_pre_monsoon_probabilistic_flash_flood_forecast',
                'managed': True,
            },
        ),
    ]
