# Generated by Django 4.1 on 2026-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0060_ukmetpremonsoonprobabilisticflashfloodforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMDWRFPreMonsoonBasinWiseFlashFloodForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'bmd_wrf_pre_monsoon_basin_wise_flash_flood_forecast',
                'managed': True,
            },
        ),
    ]
