# Generated by Django 4.1 on 2026-04-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0061_bmdwrfpremonsoonbasinwiseflashfloodforecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waterlevelobservation',
            unique_together={('station_id', 'observation_date')},
        ),
    ]
