# Generated by Django 4.1 on 2026-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0062_alter_waterlevelobservation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecmwf_Pre_Monsoon_Basin_Wise_Flash_Flood_Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('basin_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('thresholds', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'ecmwf_pre_monsoon_basin_wise_flash_flood_forecast',
            },
        ),
    ]
