# Generated by Django 4.2.5 on 2025-04-08 13:06

import app_bulletin.agromet_bulletin.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrometBulletinSourceDestinationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField(blank=True, null=True, verbose_name='source path')),
                ('destination_path', models.TextField(blank=True, null=True, verbose_name='destination path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Agromet Bulletin Source Destination Details',
                'verbose_name_plural': 'Agromet Bulletin Source Destination Details',
            },
        ),
        migrations.CreateModel(
            name='AgrometBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_provider_details', models.TextField(blank=True, null=True, verbose_name='Header of bulletin provider')),
                ('bulletin_header_location_detail', models.TextField(blank=True, null=True, verbose_name='Top header location of bulletin')),
                ('bulletin_issue_date_details', models.TextField(blank=True, null=True, verbose_name='Date of bulletin issue')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details of bulletin')),
                ('forecast_date', models.DateField(blank=True, null=True, verbose_name='date of forecast generation')),
                ('forecast_highlight', models.TextField(blank=True, null=True, verbose_name='forecast highlights')),
                ('observed_highlight', models.TextField(blank=True, null=True, verbose_name='observed weather highlights')),
                ('next_week_forecast', models.TextField(blank=True, null=True, verbose_name='weather forecast and advisory for next one week')),
                ('glossary', models.TextField(blank=True, null=True, verbose_name='glossary')),
                ('plot_path', models.JSONField(blank=True, null=True, verbose_name='path of plots')),
                ('basin_details_list', models.JSONField(blank=True, null=True, validators=[app_bulletin.agromet_bulletin.validators.validate_integer_list])),
                ('rf_stations_list', models.JSONField(blank=True, null=True, validators=[app_bulletin.agromet_bulletin.validators.validate_integer_list])),
                ('station_json_data', models.JSONField(blank=True, null=True)),
                ('flash_flood_forecast_json', models.JSONField(blank=True, null=True)),
                ('hydrograph_details_json', models.JSONField(blank=True, null=True)),
                ('all_advisory', models.JSONField(blank=True, null=True, verbose_name='advisory for all category as JSON')),
                ('all_advisory_hide_show', models.BooleanField(blank=True, null=True, verbose_name='advisory for all category hide or show')),
                ('special_advisory', models.JSONField(blank=True, null=True, verbose_name='advisory for special category as JSON')),
                ('special_advisory_header_name', models.TextField(blank=True, null=True, verbose_name='header name of special advisory')),
                ('pdf_file_path', models.TextField(blank=True, null=True, verbose_name='path of pdf file')),
                ('advisory_year', models.TextField(blank=True, null=True, verbose_name='advisory year')),
                ('advisory_month', models.TextField(blank=True, null=True, verbose_name='advisory month')),
                ('advisory_day', models.TextField(blank=True, null=True, verbose_name='advisory date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('forecast_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agromet_bulletin_forecast_data_source_info', to='app_visualization.source')),
                ('observe_data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agromet_bulletin_observation_data_source_info', to='app_visualization.source')),
            ],
            options={
                'verbose_name': 'Agromet Bulletin',
                'verbose_name_plural': 'Agromet Bulletins',
                'managed': True,
            },
        ),
    ]
