# Generated by Django 4.1 on 2025-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('email', models.JSONField(blank=True, default=list)),
                ('phone', models.TextField(blank=True, null=True)),
                ('alternatePhone', models.TextField(blank=True, null=True)),
                ('alternatePhone1', models.TextField(blank=True, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='mobile_user/app_mobile_static_data/profile_images/')),
                ('researchInterest', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional List',
                'verbose_name_plural': 'Professionals List',
            },
        ),
    ]
