# Generated by Django 4.1 on 2025-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile_static_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='mobile_user/app_mobile_static_data/user_manual/')),
            ],
            options={
                'verbose_name': 'User Manual',
                'verbose_name_plural': 'User Manuals',
            },
        ),
    ]
