# Generated by Django 4.1 on 2025-09-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile_static_data', '0002_usermanualmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanualmodel',
            old_name='profileImage',
            new_name='path',
        ),
    ]
