# Generated by Django 4.1 on 2025-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile_static_data', '0003_rename_profileimage_usermanualmodel_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Useful Link',
                'verbose_name_plural': 'Useful Links',
            },
        ),
    ]
