# Generated by Django 4.1 on 2025-09-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile_static_data', '0004_usefullinksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsLinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Link',
                'verbose_name_plural': 'Reports Links',
            },
        ),
    ]
