# Generated by Django 4.1 on 2025-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile_static_data', '0005_reportslinksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('organogram', models.TextField(blank=True, null=True)),
                ('citizen_charter', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'Abouts Us',
            },
        ),
    ]
