# Generated by Django 4.2.5 on 2025-04-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasinDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Forecast Source Name')),
                ('shape_file_path', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Path of the shape file')),
                ('destination_path', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Path of the destination file')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='FfwcRainfallStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('basin', models.CharField(blank=True, max_length=150, null=True)),
                ('division', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('altitude', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('observe_data_source_network', models.CharField(blank=True, max_length=1024, null=True)),
                ('basin_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basin_wise_rf_obs_info', to='app_visualization.basindetails')),
            ],
            options={
                'verbose_name': 'Rainfall Station',
                'verbose_name_plural': 'Rainfall Stations',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Forecast Source Name')),
                ('name_visualize', models.CharField(blank=True, max_length=128, null=True, verbose_name='Forecast Source Name for visualization')),
                ('source_path', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Path of the source file')),
                ('destination_path', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Path of the destination file')),
                ('source_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Type of Source')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='SourceDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Source Data Type Name')),
            ],
            options={
                'verbose_name': 'Source Data Type',
                'verbose_name_plural': 'Source Data Types',
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name of state')),
                ('last_update', models.DateTimeField(verbose_name='Last Update Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modification made')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_visualization.source')),
            ],
            options={
                'verbose_name': 'System State',
                'verbose_name_plural': 'System States',
            },
        ),
        migrations.CreateModel(
            name='StreamFlowStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_path', models.CharField(blank=True, max_length=50, null=True)),
                ('station_id', models.CharField(blank=True, max_length=150, null=True)),
                ('division', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=50, null=True)),
                ('river_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('altitude', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('forecast_data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamflow_station_data_source_info', to='app_visualization.source')),
            ],
            options={
                'verbose_name': 'Stream Flow Station',
                'verbose_name_plural': 'Stream Flow Stations',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='source_data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_data_type_id', to='app_visualization.sourcedatatype'),
        ),
        migrations.CreateModel(
            name='RainfallObservation',
            fields=[
                ('rf_id', models.AutoField(primary_key=True, serialize=False)),
                ('rf_date', models.DateTimeField()),
                ('rainFall', models.DecimalField(decimal_places=2, max_digits=8)),
                ('st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rf_observation_station_wise_info', to='app_visualization.ffwcrainfallstation')),
            ],
            options={
                'verbose_name': 'Rainfall Observation',
                'verbose_name_plural': 'Rainfall Observations',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Parameter Name')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Full Parameter Name')),
                ('unit', models.CharField(blank=True, max_length=32, null=True, verbose_name='Parameter Unit')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'indexes': [models.Index(fields=['name'], name='param_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(blank=True, null=True, verbose_name='Date of Forecast Generation')),
                ('step_start', models.DateTimeField(blank=True, null=True, verbose_name='Forecast step start time')),
                ('step_end', models.DateTimeField(blank=True, null=True, verbose_name='Forecast step end time')),
                ('val_min', models.FloatField(blank=True, null=True, verbose_name='Min Value/Instant value(dir)')),
                ('val_avg', models.FloatField(blank=True, null=True, verbose_name='Average Value,')),
                ('val_max', models.FloatField(blank=True, null=True, verbose_name='Max,accumulated')),
                ('basin_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_step_basin_id', to='app_visualization.basindetails')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_visualization.parameter')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_visualization.source')),
            ],
            options={
                'verbose_name': 'Forecast Steps',
                'verbose_name_plural': 'Forecast Steps',
            },
        ),
        migrations.CreateModel(
            name='ForecastDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(blank=True, null=True, verbose_name='Date of Forecast Generation')),
                ('step_start', models.DateTimeField(blank=True, null=True, verbose_name='Forecast step start time')),
                ('step_end', models.DateTimeField(blank=True, null=True, verbose_name='Forecast step end time')),
                ('val_min', models.FloatField(blank=True, null=True, verbose_name='Min Value/Instant value(dir)')),
                ('val_avg', models.FloatField(blank=True, null=True, verbose_name='Average Value,')),
                ('val_max', models.FloatField(blank=True, null=True, verbose_name='Max,accumulated')),
                ('val_avg_day', models.FloatField(blank=True, null=True, verbose_name='Average of day')),
                ('val_avg_night', models.FloatField(blank=True, null=True, verbose_name='Average of night')),
                ('basin_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_daily_basin_id', to='app_visualization.basindetails')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_visualization.parameter')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_visualization.source')),
            ],
            options={
                'verbose_name': 'Forecast Daily',
                'verbose_name_plural': 'Forecast Daily',
            },
        ),
        migrations.AddField(
            model_name='ffwcrainfallstation',
            name='observe_data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agromet_rf_station_data_source_info', to='app_visualization.source'),
        ),
    ]
