# Generated by Django 4.2.5 on 2025-04-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfwcIMDRFObservationStationNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Ffwc IMD RF Observation Station Network',
                'verbose_name_plural': 'Ffwc IMD RF Observation Station Network',
            },
        ),
        migrations.CreateModel(
            name='RainfallObservationIMDAWSStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Rainfall Observation IMD AWS States',
                'verbose_name_plural': 'Rainfall Observation IMD AWS States',
            },
        ),
        migrations.CreateModel(
            name='RainfallObservationIMDAWSDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('imd_aws_states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imd_aws_rf_observation_states_info', to='app_visualization.rainfallobservationimdawsstates')),
            ],
            options={
                'verbose_name': 'Rainfall Observation IMD AWS Districts',
                'verbose_name_plural': 'Rainfall Observation IMD AWS Districts',
            },
        ),
        migrations.CreateModel(
            name='FfwcIMDRFObservationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('basin', models.IntegerField(blank=True, null=True)),
                ('division', models.IntegerField(blank=True, default='', null=True)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('upazilla', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
                ('altitude', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('basin_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imd_observation_station_basin_wise_rf_obs_info', to='app_visualization.basindetails')),
                ('observe_data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imd_observation_station_agromet_rf_station_data_source_info', to='app_visualization.source')),
                ('observe_data_source_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ffwc_imd_observation_station_network_info', to='app_visualization.ffwcimdrfobservationstationnetwork')),
            ],
            options={
                'verbose_name': 'Ffwc IMD RF Observation Station Network',
                'verbose_name_plural': 'Ffwc IMD RF Observation Station Networks',
            },
        ),
        migrations.CreateModel(
            name='FfwcImdRainfallObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_date', models.DateTimeField()),
                ('rainFall', models.DecimalField(decimal_places=2, max_digits=8)),
                ('st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ffwc_imd_rf_observation_station_wise_info', to='app_visualization.ffwcimdrfobservationstation')),
            ],
            options={
                'verbose_name': 'FFWC IMD Rainfall Observation',
                'verbose_name_plural': 'FFWC IMD Rainfall Observations',
            },
        ),
    ]
