# Generated by Django 4.1 on 2025-10-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visualization', '0002_ffwcimdrfobservationstationnetwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationListDDDetailsV5',
            fields=[
                ('SN', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('basin', models.IntegerField(blank=True, null=True)),
                ('division', models.IntegerField(blank=True, null=True)),
                ('division_name', models.TextField(blank=True, null=True)),
                ('division_status', models.BooleanField(blank=True, null=True)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('district_name', models.TextField(blank=True, null=True)),
                ('upazilla', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('basin_details_id', models.IntegerField(blank=True, null=True)),
                ('observe_data_source_id', models.IntegerField(blank=True, null=True)),
                ('observe_data_source_name', models.CharField(blank=True, max_length=500, null=True)),
                ('observe_data_source_path', models.CharField(blank=True, max_length=500, null=True)),
                ('observe_data_source_destination_path', models.CharField(blank=True, max_length=500, null=True)),
                ('observe_data_source_type', models.CharField(blank=True, max_length=100, null=True)),
                ('observe_data_source_name_visualize', models.CharField(blank=True, max_length=500, null=True)),
                ('observe_data_source_data_type', models.IntegerField(blank=True, null=True)),
                ('observe_data_source_data_type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('observe_data_source_network_id', models.IntegerField(blank=True, null=True)),
                ('observe_data_source_network_name', models.CharField(blank=True, max_length=500, null=True)),
                ('observe_data_source_network_is_active', models.BooleanField(default=True)),
                ('accu_rainfall_count', models.FloatField(default=-1.0)),
            ],
            options={
                'db_table': 'station_list_dd_details_v5_view',
                'managed': False,
            },
        ),
    ]
