# Generated by Django 4.1 on 2025-10-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visualization', '0003_stationlistdddetailsv5'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ffwcimdrainfallobservation',
            index=models.Index(fields=['-rf_date'], name='-rf_idx'),
        ),
        migrations.AddIndex(
            model_name='ffwcimdrainfallobservation',
            index=models.Index(fields=['-st_id'], name='-st_idx'),
        ),
        migrations.AddIndex(
            model_name='ffwcimdrainfallobservation',
            index=models.Index(fields=['-st_id', '-rf_date'], name='-st_rf_idx'),
        ),
        migrations.AddIndex(
            model_name='ffwcimdrainfallobservation',
            index=models.Index(fields=['rf_date'], name='rf_idx'),
        ),
        migrations.AddIndex(
            model_name='ffwcimdrainfallobservation',
            index=models.Index(fields=['st_id'], name='st_idx'),
        ),
        migrations.AddIndex(
            model_name='ffwcimdrainfallobservation',
            index=models.Index(fields=['st_id', 'rf_date'], name='st_rf_idx'),
        ),
    ]
