# Generated by Django 4.1 on 2025-09-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_load', '0047_stationsummaryviewmobilev1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterWatchWaterLevelStationForMobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_user', models.ForeignKey(help_text='Reference to MobileAuthUser (mobile user id).', on_delete=django.db.models.deletion.CASCADE, related_name='waterwatch_water_level_stations', to=settings.AUTH_USER_MODEL)),
                ('water_level_station', models.ForeignKey(db_column='station_id', help_text='References Station.station_id (not the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='mobile_users_water_level_station', to='data_load.station', to_field='station_id')),
            ],
            options={
                'verbose_name': 'Water Watch Water Level Station for Mobile User',
                'verbose_name_plural': 'Water Watch Water Level Stations for Mobile User',
            },
        ),
        migrations.AddIndex(
            model_name='waterwatchwaterlevelstationformobileuser',
            index=models.Index(fields=['mobile_user'], name='idx_wu_mobile_user'),
        ),
        migrations.AddIndex(
            model_name='waterwatchwaterlevelstationformobileuser',
            index=models.Index(fields=['water_level_station'], name='idx_wu_station'),
        ),
        migrations.AlterUniqueTogether(
            name='waterwatchwaterlevelstationformobileuser',
            unique_together={('mobile_user', 'water_level_station')},
        ),
    ]
