# Generated by Django 4.1 on 2025-09-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0001_initial'),
        ('app_water_watch_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waterwatchwaterlevelstationformobileuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='waterwatchwaterlevelstationformobileuser',
            name='mobile_user',
            field=models.ForeignKey(help_text='Reference to MobileAuthUser (mobile user id).', on_delete=django.db.models.deletion.CASCADE, related_name='waterwatch_water_level_stations', to='app_user_mobile.mobileauthuser'),
        ),
    ]
