# Generated by Django 4.1 on 2025-09-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0047_stationsummaryviewmobilev1'),
        ('app_user_mobile', '0001_initial'),
        ('app_water_watch_mobile', '0002_alter_waterwatchwaterlevelstationformobileuser_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelInputForMobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(blank=True, help_text='Date and time of observation (24-hour format).', null=True)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, help_text='Water level value; nullable.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_acepted', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Mobile user who created the record (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_waterlevel_inputs', to='app_user_mobile.mobileauthuser')),
                ('station', models.ForeignKey(blank=True, db_column='station_id', help_text='References Station.station_id (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_user_waterlevel_inputs', to='data_load.station', to_field='station_id')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Mobile user who last updated the record (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_waterlevel_inputs', to='app_user_mobile.mobileauthuser')),
            ],
            options={
                'verbose_name': 'Water Level Input (Mobile User)',
                'verbose_name_plural': 'Water Level Inputs (Mobile Users)',
                'db_table': 'waterwatch_waterlevel_input_for_mobile_user',
                'ordering': ('-observation_date',),
            },
        ),
        migrations.AddIndex(
            model_name='waterlevelinputformobileuser',
            index=models.Index(fields=['station'], name='idx_wli_station'),
        ),
        migrations.AddIndex(
            model_name='waterlevelinputformobileuser',
            index=models.Index(fields=['observation_date'], name='idx_wli_obs_date'),
        ),
        migrations.AddIndex(
            model_name='waterlevelinputformobileuser',
            index=models.Index(fields=['created_by'], name='idx_wli_created_by'),
        ),
    ]
