# Generated by Django 4.1 on 2025-09-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_water_watch_mobile', '0003_waterlevelinputformobileuser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='waterlevelinputformobileuser',
            table=None,
        ),
    ]
