# Generated by Django 4.1 on 2025-09-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_mobile', '0001_initial'),
        ('data_load', '0051_remove_jsonentry_entry_date_and_more'),
        ('app_water_watch_mobile', '0004_alter_waterlevelinputformobileuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterWatchRFLevelStationForMobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_user', models.ForeignKey(help_text='Reference to MobileAuthUser (mobile user id).', on_delete=django.db.models.deletion.CASCADE, related_name='waterwatch_rf_level_stations', to='app_user_mobile.mobileauthuser')),
                ('water_level_station', models.ForeignKey(db_column='station_id', help_text='References Station.station_id (not the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='mobile_users_rf_level_station', to='data_load.station', to_field='station_id')),
            ],
            options={
                'verbose_name': 'Water Watch Water Level Station for Mobile User',
                'verbose_name_plural': 'Water Watch Water Level Stations for Mobile User',
            },
        ),
        migrations.CreateModel(
            name='RFLevelInputForMobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(blank=True, help_text='Date and time of observation (24-hour format).', null=True)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, help_text='Water level value; nullable.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_acepted', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Mobile user who created the record (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rflevel_inputs', to='app_user_mobile.mobileauthuser')),
                ('station', models.ForeignKey(blank=True, db_column='station_id', help_text='References Station.station_id (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_user_rflevel_inputs', to='data_load.station', to_field='station_id')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Mobile user who last updated the record (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_rflevel_inputs', to='app_user_mobile.mobileauthuser')),
            ],
            options={
                'verbose_name': 'Water Level Input (Mobile User)',
                'verbose_name_plural': 'Water Level Inputs (Mobile Users)',
                'ordering': ('-observation_date',),
            },
        ),
        migrations.AddIndex(
            model_name='waterwatchrflevelstationformobileuser',
            index=models.Index(fields=['mobile_user'], name='idx_ru_mobile_user'),
        ),
        migrations.AddIndex(
            model_name='waterwatchrflevelstationformobileuser',
            index=models.Index(fields=['water_level_station'], name='idx_ru_station'),
        ),
        migrations.AddIndex(
            model_name='rflevelinputformobileuser',
            index=models.Index(fields=['station'], name='idx_rli_station'),
        ),
        migrations.AddIndex(
            model_name='rflevelinputformobileuser',
            index=models.Index(fields=['observation_date'], name='idx_rli_obs_date'),
        ),
        migrations.AddIndex(
            model_name='rflevelinputformobileuser',
            index=models.Index(fields=['created_by'], name='idx_rli_created_by'),
        ),
    ]
