# Generated by Django 4.1 on 2025-09-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0051_remove_jsonentry_entry_date_and_more'),
        ('app_water_watch_mobile', '0005_waterwatchrflevelstationformobileuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterwatchrflevelstationformobileuser',
            options={'verbose_name': 'Water Watch Rainfall Station for Mobile User', 'verbose_name_plural': 'Water Watch Rainfall Stations for Mobile User'},
        ),
        migrations.AlterField(
            model_name='rflevelinputformobileuser',
            name='station',
            field=models.ForeignKey(blank=True, db_column='station_id', help_text='References RainfallStation.station_id (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_user_rflevel_inputs', to='data_load.rainfallstation', to_field='station_id'),
        ),
        migrations.AlterField(
            model_name='waterwatchrflevelstationformobileuser',
            name='water_level_station',
            field=models.ForeignKey(db_column='station_id', help_text='References RainfallStation.station_id (not the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='mobile_users_rf_level_station', to='data_load.rainfallstation', to_field='station_id'),
        ),
    ]
