# Generated by Django 4.1 on 2026-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_water_watch_mobile', '0006_alter_waterwatchrflevelstationformobileuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlevelinputformobileuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterlevelinputformobileuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
