# Generated by Django 4.2.5 on 2025-04-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisseminationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='name of status')),
            ],
            options={
                'verbose_name': 'Dissemination Status',
                'verbose_name_plural': 'Dissemination Status',
            },
        ),
        migrations.CreateModel(
            name='EmailsDisseminationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='subject of email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='body of email')),
                ('attached_file', models.BinaryField(blank=True, null=True, verbose_name='pdf or any type of attached file in byte format')),
                ('attached_file_name', models.TextField(blank=True, null=True, verbose_name='name of attached file')),
                ('attached_file_path', models.TextField(blank=True, null=True, verbose_name='path of bulletin file')),
                ('email_group', models.JSONField(blank=True, null=True)),
                ('total_emails', models.JSONField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='ID of the user who created this dissemination queue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='ID of the user who last updated this dissemination queue')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dissemination.disseminationstatus')),
            ],
            options={
                'verbose_name': 'Emails Dissemination Queue',
                'verbose_name_plural': 'Emails Dissemination Queues',
                'ordering': ['-created_at'],
            },
        ),
    ]
