# Generated by Django 4.2.5 on 2025-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of mailing group')),
                ('emails', models.JSONField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='ID of the user who created this mailing list')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creations')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='ID of the user who last updated this mailing list')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
