# Generated by Django 4.2.23 on 2025-07-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndianStations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('basin_name', models.CharField(max_length=100)),
                ('river_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('division_name', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_site', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('within_ganges', models.CharField(blank=True, max_length=100, null=True)),
                ('within_brahmaputra', models.CharField(blank=True, max_length=100, null=True)),
                ('within_meghna', models.CharField(blank=True, max_length=100, null=True)),
                ('station_code', models.CharField(max_length=100, unique=True)),
                ('dangerlevel', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('warning_level', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('highest_flow_level', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Indian Station',
                'verbose_name_plural': 'Indian Stations',
                'db_table': 'indian_stations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IndianWaterLevelObservations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField()),
                ('waterlevel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, to='indian_stations.indianstations')),
            ],
            options={
                'verbose_name': 'Indian Water Level Observation',
                'verbose_name_plural': 'Indian Water Level Observations',
                'db_table': 'indian_water_level_observations',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='indianstations',
            index=models.Index(fields=['station_code'], name='idx_indian_station_code'),
        ),
        migrations.AddIndex(
            model_name='indianstations',
            index=models.Index(fields=['station_name'], name='idx_indian_station_name'),
        ),
        migrations.AddIndex(
            model_name='indianstations',
            index=models.Index(fields=['basin_name'], name='idx_indian_basin_name'),
        ),
        migrations.AddIndex(
            model_name='indianwaterlevelobservations',
            index=models.Index(fields=['station'], name='idx_water_level_station'),
        ),
        migrations.AddIndex(
            model_name='indianwaterlevelobservations',
            index=models.Index(fields=['data_time'], name='idx_water_level_data_time'),
        ),
        migrations.AddIndex(
            model_name='indianwaterlevelobservations',
            index=models.Index(fields=['station', 'data_time'], name='idx_wl_st_data_time'),
        ),
    ]
