[
  {
    "id": 1,
    "key": 'udoy',
    "name": 'Sarder Udoy Raihan',
    "title": 'Executive Engineer (CC)',
    "organization": 'Flood Forecasting and Warning Centre, Bangladesh Water Development Board',
    "education": 'M.Sc. and B.Sc. in Water Resources Engg. (BUET)',
    "email": ['exen.ffwc@gmail.com', 'udoyraihan@gmail.com'],
    "phone": '+88 02 2222 30071',
    "alternatePhone1": '+880-1318234962',
    "alternatePhone": '+880-1552353433',
    "profileImage": '/assets/staff/UdoyRaihan.JPG',
    "researchInterest": 'Hydrological and Hydrodynamic Modeling, Long Range Flood Forecasting, Flash Flood  Forecasting, Satellite Based Information for Flood Forecasting, Regional Flood Forecasting System, Climate Change Issue in Flood Management, Computer Programming,  Algorithm Development.'
  },
  {
    "id": 5,
    "key": "partho",
    "name": "Partho Protim Barua",
    "title": "Sub-Divisional Engineer",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "B.Sc. in Civil Engg. (BUET), M.Sc. in Water Resources Development (BUET)",
    "email": ["dhrubo.06@gmail.com"],
    "phone": "+88 02 2222 30073",
    "alternatePhone": "+8801765405576",
    "alternatePhone1": '+8801318234963',
    "profileImage": "/assets/staff/Partho.jpg",
    "researchInterest": "Long Range & Flash Flood Forecasting, Hydrological modeling, Automation of Flood Modeling, WRF, Satellite Based information for Flood Forecasting, Modernization of Hydrological Network, Flood Plain Management, Climate Change Issues in Flood Management."
  },
  {
    "id": 6,
    "key": "mehadi",
    "name": "Mehadi Hasan",
    "title": "Sub-Divisional Engineer",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "B.Sc. in Civil Engg. (CUET)",
    "email": ["hasanmehadi875@gmail.com"],
    "phone": "+88 02 2222 30072",
    "alternatePhone": "+880-1674356208",
    "profileImage": "/assets/staff/Mehadi.jpg",
    "researchInterest": "Flood risk management, Hydrological modeling, Flood modeling for management, Long Range Flood Forecasting, Flash Flood Forecasting, Regional Flood Forecasting System, Climate Change Issues in Flood Management, Community Based Flood Warning System."
  },
  {
    "id": 7,
    "key": "tareq",
    "name": "A.N.M. Tareq Siddiquee",
    "title": "Programmer (Attached)",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "M.A. (1st Part) under Dhaka University, Diploma in Computer Science (Dhaka University)",
    "email": ["nasim_tareq@yahoo.com"],
    "phone": "+88 02 2222 30070",
    "alternatePhone": "+880-1552362560",
    "profileImage": "/assets/staff/TS Picture.jpg",
    "researchInterest": "Data Base Management for Flood Forecasting model, Regional Flood Forecasting System, Internet and computer networking."
  },
  {
    "id": 8,
    "key": "nusrat",
    "name": "Nusrat Jahan Zerin",
    "title": "Assistant Engineer",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "B.Sc. in Civil Engg. (KUET)",
    "email": ["zerinnj@gmail.com"],
    "phone": "+88 02 2222 30070",
    "alternatePhone": "+8801687024430",
    "profileImage": "/assets/staff/Zerin.jpg",
    "researchInterest": "Hydrological and Hydraulic Modelling, Flash Flood, Real-time Flood Forecasting and Digital Twining, Ensemble Forecasting and Uncertainty Quantification, Community-Based Early Warning Systems, Water Sensitive Urban Design, Blockchain for Flood Risk Management, Integrated Flood Risk Management, Resilience, Vulnerability and Equity, Climate Change Adaptation and Sustainable Solutions for Flood Management."
  },
  {
    "id": 9,
    "key": "emon",
    "name": "Emon Kalyan Das",
    "title": "Assistant Engineer",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "B.Sc. in Civil Engg. (BUET)",
    "email": ["emon@ffwc.gov.bd"],
    "phone": "+88 02 2222 30070",
    "alternatePhone": "+8801754001805",
    "profileImage": "/assets/staff/Kalyan.JPG",
    "researchInterest": "Hydrological and hydrodynamic modelling, Climate change adaptation for flood management, Automation of flood modelling, Satellite based information for flood forecasting, long range & flash flood forecasting, Community-based early warning systems and integrated flood risk management."
  },
  {
    "id": 10,
    "key": "shovon",
    "name": "Md. Mahmudul Islam Shovon",
    "title": "Assistant Engineer",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "B.Sc. in Civil Engg. (BUET)",
    "email": ["shovon.bwdb@gmail.com"],
    "phone": "+88 02 2222 30070",
    "alternatePhone": "+880-1782445538",
    "profileImage": "/assets/staff/Shovon.png",
    "researchInterest": "Flash Flood Forecasting, Smart Cities and Flood Resilient Urban Planning, Assessing Climate Change-Induced Shifts in Flood Patterns, Community-Based Flood Resilience Strategies, Satellite Based Information for Flood Forecasting, Drought Forecasting."
  },
  {
    "id": 11,
    "key": "jihan",
    "name": "Mostafa Kamal Jihan",
    "title": "Assistant Engineer",
    "organization": "Flood Forecasting and Warning Centre, Bangladesh Water Development Board",
    "education": "B.Sc. in Civil Engg. (BUET)",
    "email": ["jihan@ffwc.gov.bd"],
    "phone": "+88 02 2222 30070",
    "alternatePhone": "+880-1609980661",
    "profileImage": "/assets/staff/Jihan.jpg",
    "researchInterest": "Long Range Flood Forecasting, Flash Flood Forecasting, Climate Change Issues in Flood Management, Regional Flood Forecasting System, Community Based Flood Warning System, Smart Cities and Flood Resilient Urban Planning, Satellite Based information for Flood Forecasting, Drought Forecasting."
  }
]