# Generated by Django 4.2.23 on 2025-07-02 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indian_stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_load', '0016_ffwclastupdatedateexperimental'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoadProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'data_load_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataLoadProfileUserprofileindianstations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.BigIntegerField()),
                ('indianstations_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'data_load_profile_userProfileIndianStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataLoadProfileUserprofilestations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.BigIntegerField()),
                ('station_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'data_load_profile_userProfileStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userProfileIndianStations', models.ManyToManyField(db_constraint=False, to='indian_stations.indianstations')),
                ('userProfileStations', models.ManyToManyField(db_constraint=False, to='data_load.station')),
            ],
        ),
    ]
