# Generated by Django 4.2.23 on 2025-07-02 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userauth_userprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAuthProfileIndianStations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.BigIntegerField()),
                ('indianstations_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'userauth_profile_indianstations',
                'managed': True,
                'unique_together': {('profile_id', 'indianstations_id')},
            },
        ),
        migrations.CreateModel(
            name='UserAuthProfileStations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.BigIntegerField()),
                ('station_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'userauth_profile_stations',
                'managed': True,
                'unique_together': {('profile_id', 'station_id')},
            },
        ),
        migrations.DeleteModel(
            name='DataLoadProfile',
        ),
        migrations.DeleteModel(
            name='DataLoadProfileUserprofileindianstations',
        ),
        migrations.DeleteModel(
            name='DataLoadProfileUserprofilestations',
        ),
    ]
