# Generated by Django 4.2.23 on 2025-07-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_userauthprofile_userauthprofileindianstations_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userauthprofileindianstations',
            table='userauth_userprofile_indianstations',
        ),
        migrations.AlterModelTable(
            name='userauthprofilestations',
            table='userauth_userprofile_stations',
        ),
    ]
